name: Consolidate & Push (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  consolidate-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Consolidate duplicates & prepare commit
        run: |
          set -euo pipefail
          mkdir -p .github/backup/duplicates
          python3 - <<'PY'
import hashlib, os, shutil
seen={}
root='.'
for dirpath, dirnames, files in os.walk(root):
    if dirpath.startswith('./.git') or dirpath.startswith('./.github/backup'):
        continue
    for f in files:
        p=os.path.join(dirpath,f)
        try:
            with open(p,'rb') as fh:
                h=hashlib.sha1(fh.read()).hexdigest()
        except Exception:
            continue
        if h in seen:
            os.makedirs('.github/backup/duplicates', exist_ok=True)
            dst=os.path.join('.github/backup/duplicates', os.path.basename(p))
            base=dst; idx=1
            while os.path.exists(dst):
                dst=f"{base}.{idx}"; idx+=1
            shutil.move(p, dst)
        else:
            seen[h]=p
print("Duplicate consolidation complete")
PY

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Consolidate duplicates (Action run)"
            git push origin HEAD:main || echo "Push failed; PR fallback will be used"

      - name: Create PR fallback (if push failed)
        run: |
          set -e
          # If push failed above, create a branch and PR
          TIMESTAMP=$(date -u +%Y%m%d%H%M%S)
          BRANCH="consolidate/${TIMESTAMP}"
          git checkout -b "$BRANCH"
          git push -u origin "$BRANCH"
          API_JSON=$(jq -n --arg t "Consolidate duplicates" --arg b "Automated consolidation" --arg head "$BRANCH" --arg base "main" '{title:$t, body:$b, head:$head, base:$base}')
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" -d "$API_JSON" || true
